### ISSUE TITLE
volodya - `transferERCToBridge` will not work for some tokens that don't support approve `2**256 - 1` amount.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-telcoin-judging#1]
volodya

medium

# `transferERCToBridge` will not work for some tokens that don't support approve `2**256 - 1` amount.

## Summary
`transferERCToBridge` will not work for some tokens that don't support approve `2**256 - 1` amount.
## Impact
There are tokens that don't support approve spender `2**256 - 1` amount. So the transferERCToBridge will not work for some tokens like UNI who will revert when approve `2**256 - 1` amount. `Uni` is on the list that project promise to support

```solidity
    function approve(address spender, uint rawAmount) external returns (bool) {
        uint96 amount;
        if (rawAmount == uint(-1)) {
            amount = uint96(-1);
        } else {
345:       amount = safe96(rawAmount, "Uni::approve: amount exceeds 96 bits");
        }

        allowances[msg.sender][spender] = amount;

        emit Approval(msg.sender, spender, amount);
        return true;
    }
```
[code#L345](https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#code#L345)
## Code Snippet
```solidity
31:  uint256 constant public MAX_INT = 2**256 - 1;

70:  if (balance > IERC20Upgradeable(token).allowance(recipient, PREDICATE_ADDRESS)) {IERC20Upgradeable(token).safeApprove(PREDICATE_ADDRESS, MAX_INT);}

```
[RootBridgeRelay.sol#L70](https://github.com/sherlock-audit/2023-02-telcoin/blob/main/telcoin-audit/contracts/bridge/RootBridgeRelay.sol#L70)
## Tool used

Manual Review

## Recommendation
```solidity
if (balance > IERC20Upgradeable(token).allowance(recipient, PREDICATE_ADDRESS)) {
IERC20Upgradeable(token).safeApprove(PREDICATE_ADDRESS,
      balance - IERC20Upgradeable(token).allowance(recipient, PREDICATE_ADDRESS)
    );}

}

```

**Comment by dmitriia** [comment]
Looks ok (PR#11)

**Comment by whoismatthewmc1** [comment]
Escalate for 10 USDC.

While the reasoning is not bad, the finding is invalid for all coins supported in the [supported ERC20 token list](https://tokenlists.org/token-list?url=https://raw.githubusercontent.com/telcoin/token-lists/master/telcoins.json) as listed on the contest page.
UNI in particular, handles approval of `2 ** 256 - 1` as a special case. Note the `if (rawAmount == uint(-1))` clause from the UNI token contract below:
```
    function approve(address spender, uint rawAmount) external returns (bool) {
        uint96 amount;
342:    if (rawAmount == uint(-1)) {
            amount = uint96(-1);
        } else {
345:       amount = safe96(rawAmount, "Uni::approve: amount exceeds 96 bits");
        }
        ...
```
https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#code#L342

The UNI contract uses solidity ^0.5.16, where `uint(-1)` was commonly used as MAX_INT,
ie: `uint(-1) == 2 ** 256 - 1` can be verified in Remix using compiler version 0.5.16.

As used in RootBridgeRelay, the function will not end up reverting due to the `else` clause.
Instead, it will go through the `if` clause resulting in `amount = uint96(-1)` (which is `2 ** 96 - 1`, equivalent to `type(uint96).max` in modern solidity versions).

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> While the reasoning is not bad, the finding is invalid for all coins supported in the [supported ERC20 token list](https://tokenlists.org/token-list?url=https://raw.githubusercontent.com/telcoin/token-lists/master/telcoins.json) as listed on the contest page.
> UNI in particular, handles approval of `2 ** 256 - 1` as a special case. Note the `if (rawAmount == uint(-1))` clause from the UNI token contract below:
> ```
>     function approve(address spender, uint rawAmount) external returns (bool) {
>         uint96 amount;
> 342:    if (rawAmount == uint(-1)) {
>             amount = uint96(-1);
>         } else {
> 345:       amount = safe96(rawAmount, "Uni::approve: amount exceeds 96 bits");
>         }
>         ...
> ```
> https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#code#L342
> 
> The UNI contract uses solidity ^0.5.16, where `uint(-1)` was commonly used as MAX_INT,
> ie: `uint(-1) == 2 ** 256 - 1` can be verified in Remix using compiler version 0.5.16.
> 
> As used in RootBridgeRelay, the function will not end up reverting due to the `else` clause.
> Instead, it will go through the `if` clause resulting in `amount = uint96(-1)` (which is `2 ** 96 - 1`, equivalent to `type(uint96).max` in modern solidity versions).

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by spyrosonic10** [comment]
Escalate for 10 USDC.

I agree with comment of @whoismatthewmc1  . This doesn't seems to be a valid issue.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> I agree with comment of @whoismatthewmc1  . This doesn't seems to be a valid issue.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation accepted

Not a valid issue
As pointed out in the escalation UNI token works as expected

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Not a valid issue
> As pointed out in the escalation UNI token works as expected

This issue's escalations have been accepted!

Contestants' payouts and scores will be updated according to the changes made on this issue.
