### ISSUE TITLE
csanuragjain - Failed plugin does not cause revert

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-telcoin-judging#16]
csanuragjain

medium

# Failed plugin does not cause revert

## Summary
In case of any staking changes, all plugins are notified so that associated user state can be updated. It seems that if a plugin notification fails then also staking change operation is not reverted

## Vulnerability Detail
1. User A makes a stake which makes call to `_notifyStakeChangeAllPlugins` to notify plugins of this new stake 
2. `_notifyStakeChangeAllPlugins` continues executing even if one of the plugin call for `notifyStakeChange` fails

```solidity
function _notifyStakeChangeAllPlugins(address account, uint256 amountBefore, uint256 amountAfter) private {
        // loop over all plugins
        for (uint256 i = 0; i < nPlugins; i++) {
            // only notify if the plugin requires
            if (IPlugin(plugins[i]).requiresNotification()) {
                try IPlugin(plugins[i]).notifyStakeChange(account, amountBefore, amountAfter) {}
                catch {
                    emit StakeChangeNotificationFailed(plugins[i]);
                }
            }
        }
    }
```

## Impact
An unnotified plugin will not be able to update user state properly and may behave unexpectedly

## Code Snippet
https://github.com/sherlock-audit/2023-02-telcoin/blob/main/telcoin-audit/contracts/staking/StakingModule.sol#L491-L496

## Tool used
Manual Review

## Recommendation
Revert if any `notifyStakeChange` fails on any plugin

**Comment by hrishibhat** [comment]
Sponsor comment:
> I would say its not a valid issue. We have that code in a try{} catch{} block to allow the staking contract to continue to work despite a broken plugin. The idea is that if something was wrong with one plugin, then it could potentially block a handful different user interactions. This allows everything to continue to work. We "log" that an error occurred but we dont want to the entire contract to potentially come to a standstill.
