### ISSUE TITLE
dec3ntraliz3d - Incorrect Claimable Balance Adjustment possible in FeeBuyback  `submit` function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-02-telcoin-judging#35]
dec3ntraliz3d

medium

# Incorrect Claimable Balance Adjustment possible in FeeBuyback  `submit` function

## Summary

The FeeBuyBack contract's `submit` function may incorrectly update recipients' claimable balance.

## Vulnerability Detail

The problem is related to the following line of code, which appears a couple of times in the `submit` function.

```solidity
require(_referral.increaseClaimableBy(recipient, _telcoin.balance(address(this))), "FeeBuyback: balance was not adjusted");
```
The issue is that the Telcoin token balance of the contract might be higher than what the claimable amount should be. This may happen if some tokens are accidentally sent to the contract address. So the claimable amount will be higher than what is available.

Consider the following scenario:

1. Someone accidentally sends 1000 Telcoin to the FeeBuyback contract.
2. A submit function call occurs when the extra Telcoin is still in the contract.
3. The recipient of the `submit` call can now claim an extra 1000 Telecoin.
4. Now the extra `Telcoin` funds can not be recovered anymore because it would've been transferred to the referer contract.

## Impact

The impact of this issue is that recipients might receive more tokens than they are supposed to when claiming rewards. This could lead to an unintentional distribution of tokens.

## Code Snippet
First Occurance:
[Link to Github code](https://github.com/sherlock-audit/2023-02-telcoin/blob/main/telcoin-audit/contracts/staking/FeeBuyback.sol#L64)

```solidity
 if (token == address(_telcoin)) {
      _telcoin.safeTransferFrom(safe, address(this), amount);
      _telcoin.safeApprove(address(_referral), _telcoin.balanceOf(address(this)));
      require(_referral.increaseClaimableBy(recipient, _telcoin.balanceOf(address(this))), "FeeBuyback: balance was not adjusted");
      return true;
    }
```
Second Occurance:
[Link to Github code](https://github.com/sherlock-audit/2023-02-telcoin/blob/main/telcoin-audit/contracts/staking/FeeBuyback.sol#L81)

```solidity
   (bool swapResult,) = _aggregator.call{value: msg.value}(swapData);
    require(swapResult, "FeeBuyback: swap transaction failed");
    _telcoin.safeApprove(address(_referral), _telcoin.balanceOf(address(this)));
    require(_referral.increaseClaimableBy(recipient, _telcoin.balanceOf(address(this))), "FeeBuyback: balance was not adjusted");
    return true;
```

## Tool used

Manual Review

## Recommendation

To fix the issue, the following changes should be made in the submit function:

When the token is `telcoin`  just use `amount` to `approve` the referer contract and also the claimable amount of the recipient. 

```diff

         if (token == address(_telcoin)) {
             _telcoin.safeTransferFrom(safe, address(this), amount);
-            _telcoin.safeApprove(
-                address(_referral),
-                _telcoin.balanceOf(address(this))
-            );
+            _telcoin.safeApprove(address(_referral), amount);
             require(
-                _referral.increaseClaimableBy(
-                    recipient,
-                    _telcoin.balanceOf(address(this))
-                ),
+                _referral.increaseClaimableBy(recipient, amount),
                 "FeeBuyback: balance was not adjusted"
             );
             return true;

```

For the secondary swap scenario, calculate the difference between the Telcoin balance of the contract before and after the swap.

```diff
       //Perform secondary swap from fee token to TEL
         //do simple transfer from and submit
+        uint256 balanceBefore = _telcoin.balanceOf(address(this));
         (bool swapResult, ) = _aggregator.call{value: msg.value}(swapData);
         require(swapResult, "FeeBuyback: swap transaction failed");
-        _telcoin.safeApprove(
-            address(_referral),
-            _telcoin.balanceOf(address(this))
-        );
+        uint256 swappedAmount = _telcoin.balanceOf(address(this)) -
+            balanceBefore;
+        _telcoin.safeApprove(address(_referral), swappedAmount);
         require(
-            _referral.increaseClaimableBy(
-                recipient,
-                _telcoin.balanceOf(address(this))
-            ),
+            _referral.increaseClaimableBy(recipient, swappedAmount),
             "FeeBuyback: balance was not adjusted"
         );
         return true;

```

**Comment by dec3ntraliz3d** [comment]
Escalate for 10 USDC. 

I would argue that this is still a valid issue. If someone accidentally sends **Telcoin**  to the FeeBuyback contract, those funds won't be able to be rescued if a `submit` function is called before the rescue attempt.

I modified below test in the Feebuyback.js file.  Before calling the `submit` function some Telcoin token is sent directly to the contract. When the `submit` function  is called, that extra token goes to the referer ( yield source) which is a bug.  Now the Telcoin that was sent to the contract directly can't be rescued using `rescueERC20` function. 

Let me know if you have any questions.

```js
  it("submit with telcoin", async () => {
      //passSwap
      
      // Send some Telecoin to the feeBuyback contract
      tokenB.connect(coinbase).transfer(feeBuyback.address, "10");

      let walletData =
        "0x0bb11400" +
        ethers.utils.defaultAbiCoder
          .encode(
            ["address", "address", "address", "uint256", "uint256"],
            [swapper.address, tokenA.address, tokenB.address, "3", "4"]
          )
          .slice(2);
      await feeBuyback
        .connect(coinbase)
        .submit(
          wallet.address,
          walletData,
          safe.address,
          tokenB.address,
          recipient.address,
          "10", 
          "0x"
        );

      expect(await tokenA.balanceOf(swapper.address)).to.equal("3");
      expect(await tokenB.balanceOf(wallet.address)).to.equal("4");

      //  buyback contract will send 10 + 10 (sent directly to the contract) instead of 10
      expect(await tokenB.balanceOf(yieldSource.address)).to.equal("20");
    });
```

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC. 
> 
> I would argue that this is still a valid issue. If someone accidentally sends **Telcoin**  to the FeeBuyback contract, those funds won't be able to be rescued if a `submit` function is called before the rescue attempt.
> 
> I modified below test in the Feebuyback.js file.  Before calling the `submit` function some Telcoin token is sent directly to the contract. When the `submit` function  is called, that extra token goes to the referer ( yield source) which is a bug.  Now the Telcoin that was sent to the contract directly can't be rescued using `rescueERC20` function. 
> 
> Let me know if you have any questions.
> 
> ```js
>   it("submit with telcoin", async () => {
>       //passSwap
>       
>       // Send some Telecoin to the feeBuyback contract
>       tokenB.connect(coinbase).transfer(feeBuyback.address, "10");
> 
>       let walletData =
>         "0x0bb11400" +
>         ethers.utils.defaultAbiCoder
>           .encode(
>             ["address", "address", "address", "uint256", "uint256"],
>             [swapper.address, tokenA.address, tokenB.address, "3", "4"]
>           )
>           .slice(2);
>       await feeBuyback
>         .connect(coinbase)
>         .submit(
>           wallet.address,
>           walletData,
>           safe.address,
>           tokenB.address,
>           recipient.address,
>           "10", 
>           "0x"
>         );
> 
>       expect(await tokenA.balanceOf(swapper.address)).to.equal("3");
>       expect(await tokenB.balanceOf(wallet.address)).to.equal("4");
> 
>       //  buyback contract will send 10 + 10 (sent directly to the contract) instead of 10
>       expect(await tokenB.balanceOf(yieldSource.address)).to.equal("20");
>     });
> ```
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by dec3ntraliz3d** [comment]
I modified below test in the Feebuyback.js file.  Before calling the `submit` function some Telcoin token is sent directly to the contract. When the `submit` function  is called, that extra token goes to the referer ( yield source) which is a bug.  Now the Telcoin that was sent to the contract directly can't be rescued using `rescueERC20` function. 

Let me know if you have any questions.

```js
  it("submit with telcoin", async () => {
      //passSwap
      
      // Send some Telecoin to the feeBuyback contract
      tokenB.connect(coinbase).transfer(feeBuyback.address, "10");

      let walletData =
        "0x0bb11400" +
        ethers.utils.defaultAbiCoder
          .encode(
            ["address", "address", "address", "uint256", "uint256"],
            [swapper.address, tokenA.address, tokenB.address, "3", "4"]
          )
          .slice(2);
      await feeBuyback
        .connect(coinbase)
        .submit(
          wallet.address,
          walletData,
          safe.address,
          tokenB.address,
          recipient.address,
          "10", 
          "0x"
        );

      expect(await tokenA.balanceOf(swapper.address)).to.equal("3");
      expect(await tokenB.balanceOf(wallet.address)).to.equal("4");

      //  buyback contract will send 10 + 10 (sent directly to the contract) instead of 10
      expect(await tokenB.balanceOf(yieldSource.address)).to.equal("20");
    });
```

**Comment by hrishibhat** [comment]
Escalation rejected

Not a valid issue
Someone sending accidental tokens to a contract and resulting in additional distribution of rewards is not a valid issue.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Not a valid issue
> Someone sending accidental tokens to a contract and resulting in additional distribution of rewards is not a valid issue.

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
